require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path

pod 'rn-fetch-blob',
    :path => '../node_modules/rn-fetch-blob'

    pod 'GoogleSignIn', '~> 5.0.2'

target 'NeoStoreReplica' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  
  target 'NeoStoreReplicaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'NeoStoreReplica-tvOS' do
  # Pods for NeoStoreReplica-tvOS

  target 'NeoStoreReplica-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
